---
# DOCS: ./pre-commit.md
default_stages: [commit, push, manual]

repos:
  - repo: git@github.com:johnsondnz/pre-commit-coding-standards.git
    rev: v1.1.2
    hooks:
      - id: coding-standards

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.47.0
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
