name: Terraform Validation
on:
  push:
    branches:
      - "master"
      - "*"
      - "*/*"
    paths:
      - "modules/**"
  workflow_dispatch:

jobs:
  terraform:
    name: Validate Terraform Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: terraform_validate --all-files
